#!/bin/sh

# docker-scripts: skype
# 2016 Mike Kuznetsov <mike4gg@gmail.com>

uid=`id -u`
container_user=skype
docker ps -a --filter name=skype | grep Exited > /dev/null && docker rm `docker ps -aq --filter name=skype`
old_id=`docker ps -aq --filter name=skype`

if [ -z ${old_id} ]; then
    # Prepare xdg-open dir
    mkdir -p /run/user/${uid}/xdg-open-docker

    docker run \
        --cpuset-cpus 0 \
        --memory 512mb \
        -u ${uid} \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -e DISPLAY \
        -v /etc/machine-id:/etc/machine-id \
        -v /var/lib/dbus:/var/lib/dbus \
        -e PULSE_SERVER=/run/user/${uid}/pulse/native \
        -v /run/user/${uid}/pulse:/run/user/${uid}/pulse \
        -v $HOME/.config/pulse:/home/${container_user}/.config/pulse \
        --device /dev/video0 \
        -v $HOME/.config/skypeforlinux:/home/${container_user}/.config/skypeforlinux \
        -v /run/user/${uid}/xdg-open-docker:/run/user/${uid}/xdg-open-docker \
        --name skype \
        mike/skype

    # Clean up
    docker rm `docker ps -aq --filter name=skype`

else

    notify-send "Skype is already running!"

fi
